server:
  port: 8083

spring:
  application:
    name: notification-processor-service

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-processor-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
